language: perl
dist: trusty
sudo: required
branches:
  only:
    - master
before_install: make -f Makefile.travis install
script: make -f Makefile.travis test
after_success: make -f Makefile.travis after_success
